Repository GoormProject/walkit-front, pull requests merged in 2025-07, with the labels that each got.

#8 Feature: Tailwind CSS 설정 및 PostCSS v4 호환성 추가
  .coderabbit.yaml
  package-lock.json
  package.json
  postcss.config.js
  src/index.css
  tailwind.config.js
Labels: enhancement, setup

#9 [Feature] 디자인 시스템 토큰 구현 및 Figma 연동 - #5
  package-lock.json
  package.json
  src/components/DesignTokensDemo.tsx
  src/design-tokens/README.md
  src/design-tokens/figma.tokens.json
  src/design-tokens/token-converter.ts
  src/index.css
  src/pages/index.tsx
  src/styles/tokens.css
  tailwind.config.js
Labels: enhancement

#11 [Feature] Storybook 설치 및 UI 컴포넌트 시스템 구축
  .gitignore
  .storybook/main.ts
  .storybook/preview.ts
  .storybook/vitest.setup.ts
  eslint.config.js
  package-lock.json
  package.json
  src/components/DesignTokensDemo.tsx
  src/components/ui/Button.stories.tsx
  src/components/ui/Button.tsx
  src/components/ui/Card.stories.tsx
  src/components/ui/Card.tsx
  src/components/ui/Input.stories.tsx
  src/components/ui/Input.tsx
  src/components/ui/index.ts
  src/stories/Button.stories.ts
  src/stories/Button.tsx
  src/stories/Configure.mdx
  src/stories/Header.stories.ts
  src/stories/Header.tsx
  src/stories/Page.stories.ts
  src/stories/Page.tsx
  src/stories/assets/accessibility.png
  src/stories/assets/accessibility.svg
  src/stories/assets/addon-library.png
  src/stories/assets/assets.png
  src/stories/assets/avif-test-image.avif
  src/stories/assets/context.png
  src/stories/assets/discord.svg
  src/stories/assets/docs.png
  src/stories/assets/figma-plugin.png
  src/stories/assets/github.svg
  src/stories/assets/share.png
  src/stories/assets/styling.png
  src/stories/assets/testing.png
  src/stories/assets/theming.png
  src/stories/assets/tutorials.svg
  src/stories/assets/youtube.svg
  src/stories/button.css
  src/stories/header.css
  src/stories/page.css
  src/styles/tokens.css
  tailwind.config.js
  vitest.shims.d.ts
Labels: enhancement, Feature

#12 [Feature] 라우팅 뼈대 구현
  package-lock.json
  package.json
  src/App.tsx
  src/pages/friends/index.tsx
  src/pages/index.tsx
  src/pages/login/index.tsx
  src/pages/profile/edit/index.tsx
  src/pages/profile/index.tsx
  src/pages/reviews/index.tsx
  src/pages/signup/index.tsx
Labels: enhancement

#16 [Feature] 카카오 맵 API 초기화 및 위치 권한 처리 구현 - #15
  README.md
  src/components/KakaoMap.tsx
  src/components/LoadingSpinner.tsx
  src/pages/index.tsx
  src/utils/kakaoMap.ts
  src/vite-env.d.ts
Labels: Feature

#20 [Fix] 카카오 맵 SDK 클래스명 충돌 문제 해결 - #19
  src/components/KakaoMap.tsx
  src/utils/kakaoMap.ts
  src/vite-env.d.ts
Labels: bug

#22 [🚀 Feature] 산책 경로 폴리라인 마커 시각화 및 에러 처리 개선 - part 1 - #17
  src/App.tsx
  src/components/KakaoMap.tsx
  src/hooks/useTrailPaths.ts
  src/hooks/useWalkRecords.ts
  src/pages/test/index.tsx
  src/types/trail.ts
  src/types/walk.ts
  src/utils/backendApi.ts
  src/utils/converter/index.ts
  src/utils/converter/pathConverter.ts
  src/utils/converter/trailConverter.ts
  src/utils/kakaoMapApi.ts
  src/utils/mockTrailApi.ts
  src/utils/mockWalkApi.ts
  src/vite-env.d.ts
  tsconfig.app.json
Labels: enhancement, Feature

#32 [Feature] GPS 추적 기반 부드러운 마커 이동 구현
  src/App.tsx
  src/components/CustomMarker/index.tsx
  src/components/CustomMarker/styles.css
  src/components/GPSSimulator.tsx
  src/components/GPSTracker.tsx
  src/components/KakaoMap.tsx
  src/components/layout/RootLayout.tsx
  src/features/gps/gpsSlice.ts
  src/pages/index.tsx
  src/pages/test/gps-test.tsx
  src/types/map.ts
  src/utils/converter/pathConverter.ts
  src/utils/gpsErrorHandler.ts
  src/utils/kakaoMapApi.ts
  src/utils/mockGPSData.ts
Labels: enhancement, Feature
