Repository GoormProject/walkit-front, pull requests merged in 2025-08, with the labels that each got.

#47 [Feature] 지도 검색 기능 구현 및 UI/UX 개선
  localhost+2-key.pem
  localhost+2.pem
  src/App.tsx
  src/api/swagger-api.ts
  src/components/CustomMarker/index.tsx
  src/components/GPSTracker.tsx
  src/components/KakaoMap.tsx
  src/components/MapFallback.tsx
  src/components/WalkPathVisualization.tsx
  src/components/layout/Header.tsx
  src/components/layout/RootLayout.tsx
  src/components/test/AuthenticationPanel.tsx
  src/components/test/WalkControlPanel.tsx
  src/components/test/WalkRecordsList.tsx
  src/features/walk/walkSlice.ts
  src/hooks/useAuthentication.ts
  src/hooks/useWalkApi.ts
  src/pages/index.css
  src/pages/index.tsx
  src/pages/profile/index.tsx
  src/pages/test/category-search.css
  src/pages/test/category-search.tsx
  src/pages/test/index.tsx
  src/pages/test/walk-api-test.tsx
  src/pages/test/walk-full-test.tsx
  src/pages/test/walk-integration-test.tsx
  src/pages/test/walk-simple-test.tsx
  src/pages/test/walk-zustand-test.tsx
  src/store/index.ts
  src/types/map.ts
  src/types/walk.ts
  src/utils/backendApi.ts
  src/utils/gpsErrorHandler.ts
  src/utils/kakaoMapApi.ts
  src/utils/logout.ts
  src/utils/walkApi.ts
  vite.config.ts
  백엔드_연동_이슈_리포트.md
  쿠키_확인_가이드.md
Labels: enhancement, Feature

#50 [🚀Fix] 산책기록 API 연동 & GPS 추적 개선 - #37
  src/components/GPSSimulator.tsx
  src/components/GPSTracker.tsx
  src/components/test/WalkRecordsList.tsx
  src/pages/test/walk-full-test.tsx
  src/utils/mockGPSData.ts
Labels: bug

#55 [Feature] 홈 화면 바텀시트 연동 및 지도 상호작용 개선 - #54
  INFINITE_LOOP_FIX_PR.md
  PR_CHANGELOG.md
  PR_작업내용.md
  debug_zindex.js
  src/App.css
  src/App.tsx
  src/components/KakaoMap.tsx
  src/components/LoadingSpinner.tsx
  src/components/TrailBottomSheet.tsx
  src/components/TrailDetailCard.tsx
  src/components/ui/BottomSheet.tsx
  src/pages/index.css
  src/pages/index.tsx
  src/types/trail.ts
  src/vite-env.d.ts
  지도_상호작용_차단_버그_리포트.md
Labels: enhancement, Feature

#57 [Feature] 산책로 API 연동 및 경로 시각화 구현 - #56
  LLM_도움요청_프롬프트.md
  src/api/swagger-api.ts
  src/components/TrailBottomSheet.tsx
  src/components/TrailDetailCard.tsx
  src/components/ui/BottomSheet.tsx
  src/pages/index.tsx
  src/types/trail.ts
  src/utils/backendApi.ts
  src/utils/converter/trailConverter.ts
  src/vite-env.d.ts
  카카오맵_마커_폴리라인_제거_문제_분석_리포트.md
Labels: enhancement, Feature

#60 [Feature]: 날씨 API 연동
  public/icons/clothing/beanie.svg
  public/icons/clothing/cap.svg
  public/icons/clothing/gloves.svg
  public/icons/clothing/heavyjacket.svg
  public/icons/clothing/jacket.svg
  public/icons/clothing/longsleeve.svg
  public/icons/clothing/mittens.svg
  public/icons/clothing/pants.svg
  public/icons/clothing/shorts.svg
  public/icons/clothing/singlet.svg
  public/icons/clothing/sunglasses.svg
  public/icons/clothing/sunscreen.svg
  public/icons/clothing/tights.svg
  public/icons/clothing/tshirt.svg
  public/icons/clothing/vest.svg
  src/components/TrailBottomSheet.tsx
  src/hooks/useClothing.ts
  src/hooks/useWeather.ts
Labels: Feature

#62 [Fix] 날씨 아이콘 개선 및 오타 수정
  src/hooks/useClothing.ts
  src/hooks/useWeather.ts
Labels: bug

#64 [Feature] 산책 기록 기능 구현 - #41
  PR_41_walk_history.md
  package-lock.json
  package.json
  src/App.tsx
  src/components/RegisteredTrailList.tsx
  src/components/RegisteredTrailWalker.tsx
  src/components/TrailDetailCard.tsx
  src/components/WalkHistoryDetail.tsx
  src/components/WalkHistoryList.tsx
  src/hooks/useTrailPaths.ts
  src/hooks/useWalkRecords.ts
  src/pages/WalkSummary.tsx
  src/pages/index.tsx
  src/pages/profile/index.tsx
  src/pages/test/index.tsx
  src/pages/test/registered-trail-walk.tsx
  src/pages/walk-history/index.tsx
  src/types/walk.ts
  src/utils/backendApi.ts
  src/utils/mockTrailApi.ts
  src/utils/mockWalkApi.ts
  src/utils/trailProgressUtils.ts
  src/utils/walkApi.ts
  src/utils/walkUtils.ts
  tailwind.config.js
Labels: enhancement, Feature

#65 [Feature] 새로운 산책로 등록 및 리뷰 기능 구현 - #42
  PR_42_new_trail_regist.md
  public/images/placeholder-trail.jpg
  src/App.tsx
  src/components/WalkHistoryDetail.tsx
  src/components/WalkHistoryList.tsx
  src/pages/reviews/index.tsx
  src/pages/trail-register/index.tsx
  src/types/review.ts
  src/types/trail.ts
  src/utils/mockWalkApi.ts
  src/utils/reviewApi.ts
  src/utils/trailApi.ts
  src/utils/walkApi.ts
Labels: enhancement, Feature

#67 [Feature] 산책로 리뷰 기능 구현 - #44
  PR_리뷰_수정_삭제_기능.md
  index.html
  src/App.tsx
  src/components/TrailDetailCard.tsx
  src/components/TrailReviewsList.tsx
  src/pages/reviews/edit.tsx
  src/pages/reviews/index.tsx
  src/pages/test/trail-reviews-test.tsx
  src/types/review.ts
  src/utils/reviewApi.ts
  src/utils/starRating.tsx
Labels: enhancement, Feature

#69 [Feature] 친구 위치 표시 기능 구현 - #53
  PR_친구_위치_표시_기능.md
  src/components/FriendLocationMarkers.tsx
  src/hooks/index.tsx
  src/hooks/useFriendLocations.ts
  src/pages/index.tsx
  src/types/friend.ts
  src/utils/friendApi.ts
Labels: enhancement, Feature
